services:
  - type: web
    name: site_ecole
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - .env
        - app/**
        - routes/**
        - resources/**
        - public/**
        - database/**
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-mysql-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: site_ecole
      - key: DB_USERNAME
        value: your-username
      - key: DB_PASSWORD
        value: your-password
