services:
  - type: web
    name: site_ecole
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: site-ecole-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase:
          name: site-ecole-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: site-ecole-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: site-ecole-db
          property: password
